version: '3.9'

services:
  db:
    container_name: 'playlist_dev_db'
    image: postgres
    environment:
      - POSTGRES_PASSWORD: password
      - POSTGRES_USER: username
      - POSTGRES_DB: dbname
    ports:
      - 5555:5432
    volumes:
      - ./pd_data:/var/lib/postgresql/data
      # database init script
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
